import {z} from 'zod';
export const STORAGE_KEY='mi-economia.records.v1';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(d=>{const n=new Date(d+'T12:00:00Z');return !isNaN(n.getTime())&&n.toISOString().slice(0,10)===d});
const movement=z.object({id:z.string().uuid(),type:z.enum(['income','expense','withdrawal','deposit','opening','investment_open','investment_add','investment_return','investment_withdraw','investment_profit_withdraw','investment_loss','account_open','account_transfer']),amount:z.number().int().nonnegative().max(1e14),concept:z.string().trim().min(1).max(300),date,cash:z.union([z.literal(0),z.literal(1)]),origin:z.string().max(100),investmentId:z.string().uuid().optional(),accountId:z.string().uuid().optional(),targetAccountId:z.string().uuid().optional()}).superRefine((row,ctx)=>{if(row.amount===0&&row.type!=='account_open')ctx.addIssue({code:'custom',message:'El monto debe ser mayor que cero'});if(row.type.startsWith('account_')&&!row.accountId)ctx.addIssue({code:'custom',message:'Selecciona una cuenta'});if(row.type==='account_transfer'&&(!row.targetAccountId||row.targetAccountId===row.accountId))ctx.addIssue({code:'custom',message:'Selecciona otra cuenta de destino'});if(row.accountId&&row.cash&&row.type!=='withdrawal'&&row.type!=='deposit')ctx.addIssue({code:'custom',message:'Elige efectivo o cuenta'});if(row.type.startsWith('investment_')&&!row.investmentId)ctx.addIssue({code:'custom',message:'Selecciona una inversión'});});
export type Movement=z.infer<typeof movement>;
const records=z.array(movement).max(100000).superRefine((rows,ctx)=>{if(new Set(rows.map(r=>r.id)).size!==rows.length)ctx.addIssue({code:'custom',message:'Identificadores repetidos'});});
export const backupSchema=z.object({app:z.literal('mi-economia'),version:z.literal(1),movements:records});
export function readRecords(storage:Pick<Storage,'getItem'>):Movement[]{const raw=storage.getItem(STORAGE_KEY);return raw===null?[]:records.parse(JSON.parse(raw));}
export function writeRecords(storage:Pick<Storage,'setItem'>,rows:Movement[]){const valid=records.parse(rows);storage.setItem(STORAGE_KEY,JSON.stringify(valid));return valid;}
export function mergeRecords(existing:Movement[],incoming:Movement[]){const map=new Map(existing.map(r=>[r.id,r]));for(const row of incoming){const before=map.get(row.id);if(before&&JSON.stringify(before)!==JSON.stringify(row))throw Error('El respaldo contiene un registro incompatible. No cambiamos tus datos.');map.set(row.id,row);}return [...map.values()].sort((a,b)=>b.date.localeCompare(a.date));}
