'use client';
import {useEffect,useRef,useState} from 'react';
import {Cloud,RefreshCw} from 'lucide-react';
import {toast} from 'sonner';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator} from '@/components/ui/dropdown-menu';
import {DRIVE_SCOPE,DriveAuthorizationError,synchronizeDrive} from '@/lib/drive-sync';
import {readRecords,type Movement} from '@/lib/local-records';
type TokenResponse={access_token?:string;expires_in?:number;scope?:string;error?:string};
type TokenClient={requestAccessToken:(options:{prompt:string})=>void};
type GoogleOAuth={initTokenClient:(options:{client_id:string;scope:string;include_granted_scopes:boolean;callback:(response:TokenResponse)=>void;error_callback:()=>void})=>TokenClient;hasGrantedAllScopes:(response:TokenResponse,scope:string)=>boolean};
const CLIENT_KEY='mi-economia.google-client-id.v1';
function oauth(){return (window as unknown as {google?:{accounts:{oauth2:GoogleOAuth}}}).google?.accounts.oauth2;}
export default function DriveButton({onSync}:{onSync:(records:Movement[])=>void}){
 const [clientInput,setClientInput]=useState('');
 const [config,setConfig]=useState<string|null>(null),[scriptReady,setScriptReady]=useState(false),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[setup,setSetup]=useState(false),[lastSync,setLastSync]=useState(''),[failed,setFailed]=useState(false);
 const token=useRef(''),expires=useRef(0),lock=useRef(false),onSyncRef=useRef(onSync),client=useRef<TokenClient|null>(null),mounted=useRef(true),noticeShown=useRef(false),configFailed=useRef(false);
 useEffect(()=>{onSyncRef.current=onSync},[onSync]);
 async function sync(showFailure=false){if(lock.current||!token.current)return;if(Date.now()>=expires.current){token.current='';setConnected(false);setFailed(false);if(!noticeShown.current){toast.info('La autorización de Google venció. Pulsa Conectar con Drive para continuar.');noticeShown.current=true;}return;}lock.current=true;setBusy(true);try{const rows=await synchronizeDrive(token.current,window.localStorage);if(!mounted.current)return;onSyncRef.current(rows);setLastSync(new Intl.DateTimeFormat('es-CO',{hour:'2-digit',minute:'2-digit'}).format(new Date()));setFailed(false);}catch(e){if(!mounted.current)return;setFailed(true);try{onSyncRef.current(readRecords(window.localStorage))}catch{}if(e instanceof DriveAuthorizationError){token.current='';setConnected(false);}if(showFailure)toast.error(e instanceof Error?e.message:'No pudimos sincronizar.');}finally{lock.current=false;if(mounted.current)setBusy(false);}}
 useEffect(()=>{mounted.current=true;setConfig(localStorage.getItem(CLIENT_KEY)||'');if(oauth()){setScriptReady(true);}else{let script=document.getElementById('google-drive-identity') as HTMLScriptElement|null;if(!script){script=document.createElement('script');script.id='google-drive-identity';script.src='https://accounts.google.com/gsi/client';script.async=true;document.head.appendChild(script);}script.addEventListener('load',()=>{if(mounted.current)setScriptReady(true)});script.addEventListener('error',()=>{if(mounted.current)setScriptReady(false)});}return()=>{mounted.current=false;token.current='';}},[]);
 useEffect(()=>{if(!connected)return;const periodic=()=>{if(document.visibilityState==='visible'&&navigator.onLine)void sync()};const interval=setInterval(periodic,5*60*1000);window.addEventListener('online',periodic);document.addEventListener('visibilitychange',periodic);return()=>{clearInterval(interval);window.removeEventListener('online',periodic);document.removeEventListener('visibilitychange',periodic)}},[connected]);
 function connect(){if(config===null){toast.info('Preparando la conexión…');return}if(!config){setClientInput('');setSetup(true);return}if(!scriptReady||!oauth()){toast.error('No pudimos cargar Google. Revisa tu conexión e inténtalo de nuevo.');return}setBusy(true);client.current=oauth()!.initTokenClient({client_id:config,scope:DRIVE_SCOPE,include_granted_scopes:false,callback:response=>{if(!mounted.current)return;setBusy(false);if(response.error||!response.access_token||!oauth()!.hasGrantedAllScopes(response,DRIVE_SCOPE)){toast.error('No se concedió acceso al respaldo de Drive. Puedes continuar usando la app.');return}token.current=response.access_token;expires.current=Date.now()+Math.max(0,Number(response.expires_in||3600)-30)*1000;noticeShown.current=false;setConnected(true);void sync(true)},error_callback:()=>{if(mounted.current){setBusy(false);toast.info('La conexión se canceló. Tus registros siguen en el dispositivo.')}}});client.current.requestAccessToken({prompt:'select_account'});}
 const label=busy?'Sincronizando…':connected?(failed?'Reintentar Drive':'Drive conectado'):'Conectar con Drive';
 return <><div className="drivecontrol">{connected?<DropdownMenu><DropdownMenuTrigger asChild><button className="drivebutton" disabled={busy}><Cloud size={17}/>{label}</button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>void sync(true)}>Sincronizar ahora</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>{setClientInput(config||'');setSetup(true);}}>Configurar Drive</DropdownMenuItem><DropdownMenuItem onSelect={()=>{token.current='';expires.current=0;setConnected(false);setLastSync('');setFailed(false);toast.info('Drive desconectado. Los registros locales se conservan.');}}>Desconectar Drive</DropdownMenuItem></DropdownMenuContent></DropdownMenu>:<button className="drivebutton" onClick={connect} disabled={busy}>{busy?<RefreshCw className="spin" size={17}/>:<Cloud size={17}/>} {label}</button>}{!connected&&<button className="drivebutton" onClick={()=>{setClientInput(config||'');setSetup(true);}}>Configurar Drive</button>}{connected&&<small>{failed?'Pendiente de sincronizar':lastSync?'Última sincronización '+lastSync:'Conectando…'}</small>}</div><AlertDialog open={setup} onOpenChange={setSetup}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Configurar tu Google Drive</AlertDialogTitle><AlertDialogDescription>Ingresa el ID de cliente OAuth de tu proyecto de Google. Al conectar elegirás la cuenta donde guardar tus copias. Autoriza el origen https://controlesmineras.github.io en Google Cloud. No ingreses contraseñas ni secretos de cliente.</AlertDialogDescription></AlertDialogHeader><label className="drive-config-label">ID de cliente de Google<input value={clientInput} onChange={e=>setClientInput(e.target.value)} placeholder="…apps.googleusercontent.com" autoComplete="off"/></label><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><button className="save" onClick={()=>{const id=clientInput.trim();if(id&&!/^[a-zA-Z0-9._-]+\.apps\.googleusercontent\.com$/.test(id)){toast.error('Ingresa un ID de cliente válido de Google.');return;}token.current='';expires.current=0;setConnected(false);setLastSync('');localStorage.setItem(CLIENT_KEY,id);setConfig(id);setSetup(false);toast.success('Configuración guardada en este dispositivo.');}}>Guardar configuración</button></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
